/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

-- Find total customers by countries
SELECT 
	country,
    COUNT(DISTINCT customer_key) as total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers desc;

-- Find total customers by gender
SELECT 
	gender,
    COUNT(DISTINCT customer_key) as total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers desc;

-- Find total products by category
SELECT
    category,
    COUNT(DISTINCT product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- What is the average costs in each category?
SELECT
    category,
    AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC;

-- What is the total revenue generated for each category?
SELECT 
	p.category,
	SUM(sales_amount) as total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p 
    ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue desc;

-- What is the total revenue generated by each customer?
SELECT 
	c.customer_key,
    c.first_name,
    c.last_name,
	SUM(sales_amount) as total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c 
    ON c.customer_key = f.customer_key
GROUP BY
	c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue desc;

-- What is the distribution of sold items across countries?
SELECT 
 c.country,
 SUM(quantity) as total_items_sold
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c 
	ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_items_sold DESC;
